### ISSUE TITLE
Everything greyed out?

### ISSUE THREAD

**Issue by kurumushi** [flozz/calcleaner#4]
Just installed the app on flatpak, and the "add account" button is greyed out. When I click the hamburger menu, clicking "add account" does nothing, and both "about" and "quit" are also greyed out. Is there some other requirement?

Output when run from the console:

`Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/calcleaner/application.py", line 38, in do_startup
    self.accounts.load()
  File "/app/lib/python3.9/site-packages/calcleaner/accounts.py", line 25, in load
    secrets = Secret.password_search_sync(
gi.repository.GLib.GError: g-dbus-error-quark: org.freedesktop.DBus.Error.ServiceUnknown (2)
`

This is on opensuse Tumbleweed KDE.

**Comment by kurumushi** [comment]
Just solved it. The  flatpak does not by default have permission to dbus,

**Comment by flozz** [comment]
Hello,

Is it a missing permission in the CalCleaner package or is it a misconfiguration of Flatpak on your side?

**Comment by kurumushi** [comment]
Looks like it's the flatpak package itself, the permission I had to enable was "socket=session-bus" which isn't enabled in the [flatpak file](https://github.com/flathub/org.flozz.calcleaner/blob/de9c1d8496302024af1e8964a0cbc19a5340315f/org.flozz.calcleaner.yml#L6)

**Comment by flozz** [comment]
Thank you I will fix that!

**Comment by flozz** [comment]
Hum, the doc state that this permission should be used only for dev tools:

> Access to the entire bus with --socket=system-bus or --socket=session-bus should be avoided, unless the application is a development tool.

https://docs.flatpak.org/en/latest/sandbox-permissions.html#d-bus-access

I think Flatpak already give a basic access to DBus (but only to the endpoint of the app) and that additional permission is not required.

**Comment by kurumushi** [comment]
This app is trying to connect to the secret service (gnome-keyring, etc.) over dbus, with that option disabled I was unable to do so. So maybe it's using a non standard method to do it?

**Comment by flozz** [comment]
The strange thing is that it works out of the box on Ubuntu... :/

In the doc I found the `--talk-name=org.freedesktop.secrets` permission: https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html

Maybe this permission would be enough?

**Comment by flozz** [comment]
I was able to reproduce the issue in a VM. I also found other softwares that have issue in OpenSUSE, like Pika backup that is unable to access the keyring. 

Now I have to understand why on some distro it works but not on some other ones... Accessing the application own namespace on D-Bus should not require additional permission. For the keyring, on Ubuntu it seems that the portal creates a specific keyring for the app that is then stored in the main one... :thinking: 

![image](https://user-images.githubusercontent.com/971438/193763042-2078788b-a338-42af-874d-e8e4654b452d.png)
